-- CreateTable
CREATE TABLE "AuditorRtcApuracao" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "companyId" TEXT NOT NULL,
    "periodo" TEXT,
    "totalNfes" INTEGER NOT NULL,
    "totalItens" INTEGER NOT NULL,
    "canceladas" INTEGER NOT NULL,
    "denegadas" INTEGER NOT NULL,
    "validas" INTEGER NOT NULL,
    "comAlertas" INTEGER NOT NULL,
    "inconsistentes" INTEGER NOT NULL,
    "pctConformidade" REAL NOT NULL,
    "semIBS" INTEGER NOT NULL,
    "semCBS" INTEGER NOT NULL,
    "arquivosComErro" INTEGER NOT NULL DEFAULT 0,
    "processedAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "AuditorRtcApuracao_companyId_fkey" FOREIGN KEY ("companyId") REFERENCES "Company" ("id") ON DELETE CASCADE ON UPDATE CASCADE
);

-- CreateTable
CREATE TABLE "AuditorRtcNfe" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "apuracaoId" TEXT NOT NULL,
    "fileName" TEXT NOT NULL,
    "chave" TEXT,
    "nNF" TEXT,
    "serie" TEXT,
    "dhEmi" TEXT,
    "cnpjEmit" TEXT,
    "xNomeEmit" TEXT,
    "status" TEXT NOT NULL,
    "statusDetail" TEXT,
    "situacao" TEXT NOT NULL,
    "itemCount" INTEGER NOT NULL,
    "itensErro" INTEGER NOT NULL DEFAULT 0,
    "itensAlerta" INTEGER NOT NULL DEFAULT 0,
    "itensSemIBS" INTEGER NOT NULL DEFAULT 0,
    "itensSemCBS" INTEGER NOT NULL DEFAULT 0,
    "observacoes" TEXT,
    "nProt" TEXT,
    "synthetic" BOOLEAN NOT NULL DEFAULT false,
    CONSTRAINT "AuditorRtcNfe_apuracaoId_fkey" FOREIGN KEY ("apuracaoId") REFERENCES "AuditorRtcApuracao" ("id") ON DELETE CASCADE ON UPDATE CASCADE
);

-- CreateTable
CREATE TABLE "AuditorRtcItem" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "nfeId" TEXT NOT NULL,
    "nItem" TEXT,
    "xProd" TEXT,
    "cProd" TEXT,
    "ncm" TEXT,
    "cfop" TEXT,
    "tes" TEXT,
    "cClassTrib" TEXT,
    "cst" TEXT,
    "groupType" TEXT,
    "qCom" REAL,
    "vUnCom" REAL,
    "vProd" REAL,
    "vDesc" REAL,
    "vFrete" REAL,
    "vSeg" REAL,
    "vOutro" REAL,
    "vBC" REAL,
    "pIBSUF" REAL,
    "vIBSUF" REAL,
    "pIBSMun" REAL,
    "vIBSMun" REAL,
    "pIBSTotal" REAL,
    "vIBS" REAL,
    "pCBS" REAL,
    "vCBS" REAL,
    "hasIBS" BOOLEAN NOT NULL DEFAULT false,
    "hasCBS" BOOLEAN NOT NULL DEFAULT false,
    "cstPis" TEXT,
    "pPis" REAL,
    "vPis" REAL,
    "cstCofins" TEXT,
    "pCofins" REAL,
    "vCofins" REAL,
    "situacao" TEXT NOT NULL,
    "missingLabel" TEXT,
    "alertLabel" TEXT,
    CONSTRAINT "AuditorRtcItem_nfeId_fkey" FOREIGN KEY ("nfeId") REFERENCES "AuditorRtcNfe" ("id") ON DELETE CASCADE ON UPDATE CASCADE
);
