-- AlterTable
ALTER TABLE "ConciliacaoBancariaDia" DROP COLUMN "diferenca",
DROP COLUMN "saldoExtrato",
DROP COLUMN "saldoRazao",
ADD COLUMN     "diferencaEntrada" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "diferencaSaida" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "entradaExtrato" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "entradaRazao" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "saidaExtrato" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "saidaRazao" DOUBLE PRECISION NOT NULL DEFAULT 0;
